/* AUTO-GENERATED by scripts/parse-market-profiles-expanded.mjs — do not edit by hand */

export const marketProfilesMeta = {
  "title": "67 Market Profiles on Adoption",
  "subtitle": "",
  "description": "",
  "caution": "**One cross-cutting caution.** The headline rates are not comparable across countries. Eurostat and most statistics offices count *firms* (usually 10+ employees) using AI in production; Microsoft's AI Diffusion data counts *working-age individuals* using generative AI; consultancy surveys use opt-in panels skewed toward larger, digitally-engaged firms. Official figures run far below vendor figures for the same country — Saudi Arabia is 33.1% by its own statistics office [21] but 81% in a vendor survey [35]; Mexico is 0.5% of all economic units by census [24] but ~81% \"using or planning\" in vendor data; Korea ranges 6.35% to 30.3% across two official surveys in the same year [23]. Lead with the official number, and read every figure with its definition attached.",
  "referencesSummary": ""
};
